# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: incode.ca:9001/dummy/requirements-assignment-2:latest

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-service
services:
  - mongo:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - BackEnd/studentsRecords/node_modules/
  - FrontEnd/studentsRecords/node_modules/
  - FrontEnd/studentsRecords/bower_components/

# Ensure that the back passes its tests first since the front relies on the back
stages:
  - back_tests
  - front_tests

# Tell the backend where to find the MongoDB database
variables:
  MONGO_DB_HOST: "mongo"
  
# Restore the mongodb database
before_script:
  - mongorestore -h $MONGO_DB_HOST -d studentsRecords studentsRecords/

test_backend:
  stage: back_tests
  script:
   - cd BackEnd/studentsRecords
   - npm install
   - node server.js &
  after_script:
   - sleep 10 && pkill node
  allow_failure: true   # Temporary for testing purposes
# when: manual

test_frontend:
  stage: front_tests
  before_script:
   - 'echo "{ \"allow_root\": true }" > /root/.bowerrc'
  script:
   - pushd .
   - cd BackEnd/studentsRecords
   - npm install
   - node server.js &
   - popd
   - cd FrontEnd/studentsRecords
   - npm install
   - bower install
   - ember test
  after_script:
   - pkill node
#  when: manual
