# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: incode.ca:9001/se3352a/requirements-assignment-2:latest

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-service
services:
  - mongo:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - BackEnd/studentsRecords/node_modules/
  - FrontEnd/studentsRecords/node_modules/
  - FrontEnd/studentsRecords/bower_components/

before_script:
   - 'echo "{ \"allow_root\": true }" > /root/.bowerrc'

test_backend:
  script:
   - pushd .
   - cd BackEnd/studentsRecords && npm install
   - popd
   - cd BackEnd/studentsRecords && node server.js
  when: manual

test_frontend:
  script:
   - pushd .
   - cd FrontEnd/studentsRecords && npm install && bower install
   - popd
   - pushd .
   - cd BackEnd/studentsRecords && node server.js &
   - popd
   - pushd .
   - cd FrontEnd/studentsRecords && ember serve
  when: manual
