version: '3.0'
services:
  webapp:
    restart: always
    build: .
    links:
      - mongo
    ports:
      - 80
    environment:
      - VIRTUAL_HOST
      - NODE_ENV=production
      - MONGO_DB_HOST=mongo
  mongo:
    image: mongo:latest
    restart: always
  mongo-seed:
    build: ./mongo-seed
    depends_on:
      - mongo
    links:
      - mongo