version: '3.0'

restart_policy:
      condition: any
      delay: 5s
      window: 10s

services:
  webapp:
    build: .
    links:
      - mongo
    ports:
      - 80:80
    environment:
      - NODE_ENV=production
      - MONGO_DB_HOST=mongo
  mongo:
    image: mongo:latest
  mongo-seed:
    build: ./mongo-seed
    links:
      - mongo